keys:
  - &master_key age1aaqhj07jqqnqnga23jgtmnk9c3yw4ym5ff399w5s3w77kj6835ns4zhdn7
  - &host_cassian age1ula48ndvc99p9x860v5c5fjuxznqkd64e4g0leqpnk0jagj9v9tstv2fpy
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *master_key
      - *host_cassian
