keys:
  - &master_key age1aaqhj07jqqnqnga23jgtmnk9c3yw4ym5ff399w5s3w77kj6835ns4zhdn7
  - &host_cassian age1uqwrplqd78sxd3seknpd9kk76r2xny5vhag3w3mrhe35f6st89ps5s8gl9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *master_key
      - *host_cassian
