keys:
  users:
    - &master age1aaqhj07jqqnqnga23jgtmnk9c3yw4ym5ff399w5s3w77kj6835ns4zhdn7
  hosts:
    - &cassian age1su5c4cpsv73f8er7ct2sg7vm5n4nvdstgelgltmr3s2m70597a5quhmaz4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *master
        - *cassian
