keys:
  users:
    - &shell age1603gln7maw6q89mat0pz56c77928xs3qvm2hx5gnnkpnsv4ekgcqx6v983
  hosts:
    - &cassian age1az02rvvdnmu9h3jrncx7xra60dlcgejacja9sfep00arpevd0d5sspsz6s
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *shell
        - *cassian
